/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package net.chompsoftware.knes

import net.chompsoftware.knes.hardware.*
import kotlin.system.measureTimeMillis


class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

@ExperimentalUnsignedTypes
fun main() {
    println("Starting")
    val time = measureTimeMillis {
        val memory = Memory(setupMemory(LDA_AB, 0x01u, 0x00u))
        val cpu = CpuState(0, 0x0u)
        for (i in 1..40_000_000) {

//            processInstruction(cpu, memory).forEach {  }
            processInstructionPL(cpu, memory)
            if(cpu.programCounter != 3 || cpu.aReg != memory[1]) {
                throw Error("CPU State Incorrect")
            }
            cpu.programCounter = 0
            cpu.aReg = 0u
        }
    }
    println("Took: $time")

}
